#include "Zombatar.h"
#include "../../Resources.h"
#include "../../ConstEnums.h"
using namespace Sexy;
Color gZombatarSkinPalletes[] = {
    Color(204, 255, 51),
    Color(153, 204, 51),
    Color(102, 153, 51),
    Color(51, 102, 51),
    Color(255, 255, 102),
    Color(255, 204, 102),
    Color(255, 153, 102),
    Color(255, 102, 102),
    Color(255, 51, 102),
    Color(204, 204, 255),
    Color(153, 153, 255),
    Color(102, 102, 255)
};

Color gZombatarDimPalletes[] = {
    Color(255, 255, 255),
    Color(165, 165, 165),
    Color(100, 100, 100),
    Color(255, 100, 100),
    Color(255, 200, 100),
    Color(255, 255, 100),
    Color(100, 255, 100),
    Color(100, 100, 255),
    Color(200, 100, 255),
    Color(255, 100, 255),
    Color(139, 69, 19),
    Color(0, 0, 0),
    Color(255, 215, 0),
    Color(192, 192, 192),
    Color(255, 140, 0),
    Color(128, 0, 128),
    Color(0, 128, 0)
};

Color gZombatarBrightPalletes[] = {
    Color(255, 255, 255),
    Color(200, 200, 200),
    Color(150, 150, 150),
    Color(255, 150, 150),
    Color(255, 225, 150),
    Color(255, 255, 150),
    Color(150, 255, 150),
    Color(150, 150, 255),
    Color(225, 150, 255),
    Color(255, 150, 255),
    Color(160, 82, 45),
    Color(50, 50, 50),
    Color(255, 223, 0),
    Color(211, 211, 211),
    Color(255, 165, 0),
    Color(139, 0, 139),
    Color(0, 100, 0)
};

ZombatarDefinition gZombatarDefinitions[] = {
	{ZombatarItem::ZOMBATAR_BACKGROUND_CRAZYDAVE,	nullptr,							&Sexy::IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE,	ZombatarCategory::ZombatarCategory_Backdrops,	  0, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_BACKGROUND_MENU,	    nullptr,							&Sexy::IMAGE_ZOMBATAR_BACKGROUND_MENU,		ZombatarCategory::ZombatarCategory_Backdrops,	  1, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_BACKGROUND_MENU_DOS,    nullptr,							&Sexy::IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS,  ZombatarCategory::ZombatarCategory_Backdrops,	  2, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_BACKGROUND_ROOF,	    nullptr,							&Sexy::IMAGE_ZOMBATAR_BACKGROUND_ROOF,		ZombatarCategory::ZombatarCategory_Backdrops,	  3, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_BACKGROUND_BLANK,		nullptr,							&Sexy::IMAGE_ZOMBATAR_BACKGROUND_BLANK,		ZombatarCategory::ZombatarCategory_Backdrops,	  4, 0,		gZombatarBrightPalletes},
	
	{ZombatarItem::ZOMBATAR_HAIR_1,					&Sexy::IMAGE_ZOMBATAR_HAIR_1,		&Sexy::IMAGE_ZOMBATAR_HAIR_1_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  0, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_2,					&Sexy::IMAGE_ZOMBATAR_HAIR_2,		&Sexy::IMAGE_ZOMBATAR_HAIR_2_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  1, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_3,					&Sexy::IMAGE_ZOMBATAR_HAIR_3,		nullptr,									ZombatarCategory::ZombatarCategory_Hairs,		  2, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_HAIR_4,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_4,				ZombatarCategory::ZombatarCategory_Hairs,		  3, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_5,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_5,				ZombatarCategory::ZombatarCategory_Hairs,		  4, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_6,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_6,				ZombatarCategory::ZombatarCategory_Hairs,		  5, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_7,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_7,				ZombatarCategory::ZombatarCategory_Hairs,		  0, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_8,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_8,				ZombatarCategory::ZombatarCategory_Hairs,		  1, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_9,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_9,				ZombatarCategory::ZombatarCategory_Hairs,		  2, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_10,				nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_10,				ZombatarCategory::ZombatarCategory_Hairs,		  3, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_11,				&Sexy::IMAGE_ZOMBATAR_HAIR_11,		&Sexy::IMAGE_ZOMBATAR_HAIR_11_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  4, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_12,				&Sexy::IMAGE_ZOMBATAR_HAIR_12,		&Sexy::IMAGE_ZOMBATAR_HAIR_12_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  5, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_13,				&Sexy::IMAGE_ZOMBATAR_HAIR_13,		&Sexy::IMAGE_ZOMBATAR_HAIR_13_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  0, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_14,				&Sexy::IMAGE_ZOMBATAR_HAIR_14,		&Sexy::IMAGE_ZOMBATAR_HAIR_14_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  1, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_15,				&Sexy::IMAGE_ZOMBATAR_HAIR_15,		&Sexy::IMAGE_ZOMBATAR_HAIR_15_MASK,			ZombatarCategory::ZombatarCategory_Hairs,		  2, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_HAIR_16,				nullptr,							&Sexy::IMAGE_ZOMBATAR_HAIR_16,				ZombatarCategory::ZombatarCategory_Hairs,		  3, 2,		gZombatarDimPalletes},
    
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_1,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_1_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_1,		ZombatarCategory::ZombatarCategory_FacialHair,	  0, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_2,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_2,		ZombatarCategory::ZombatarCategory_FacialHair,	  1, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_3,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_3,		ZombatarCategory::ZombatarCategory_FacialHair,	  2, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_4,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_4_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_4,		ZombatarCategory::ZombatarCategory_FacialHair,	  3, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_5,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_5,		ZombatarCategory::ZombatarCategory_FacialHair,	  4, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_6,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_6,		ZombatarCategory::ZombatarCategory_FacialHair,	  5, 0,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_7,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_7,		ZombatarCategory::ZombatarCategory_FacialHair,	  0, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_8,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_8_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_8,		ZombatarCategory::ZombatarCategory_FacialHair,	  1, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_9,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_9_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_9,		ZombatarCategory::ZombatarCategory_FacialHair,	  2, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_10,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_10,	ZombatarCategory::ZombatarCategory_FacialHair,	  3, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_11,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_11,	ZombatarCategory::ZombatarCategory_FacialHair,	  4, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_12,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_12,	ZombatarCategory::ZombatarCategory_FacialHair,	  5, 1,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_13,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_13,	ZombatarCategory::ZombatarCategory_FacialHair,	  0, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_14,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_14,	ZombatarCategory::ZombatarCategory_FacialHair,	  1, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_15,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_15,	ZombatarCategory::ZombatarCategory_FacialHair,	  2, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_16,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_16,	ZombatarCategory::ZombatarCategory_FacialHair,	  3, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_17,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_17,	ZombatarCategory::ZombatarCategory_FacialHair,	  4, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_18,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_18,	ZombatarCategory::ZombatarCategory_FacialHair,	  5, 2,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_19,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_19,	ZombatarCategory::ZombatarCategory_FacialHair,	  0, 3,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_20,			nullptr,							&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_20,	ZombatarCategory::ZombatarCategory_FacialHair,	  1, 3,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_21,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_21_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_21,	ZombatarCategory::ZombatarCategory_FacialHair,	  2, 3,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_22,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_22_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_22,	ZombatarCategory::ZombatarCategory_FacialHair,	  3, 3,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_23,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_23_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_23,	ZombatarCategory::ZombatarCategory_FacialHair,	  4, 3,		gZombatarDimPalletes},
	{ZombatarItem::ZOMBATAR_FACIAL_HAIR_24,			&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_24_MASK,	&Sexy::IMAGE_ZOMBATAR_FACIALHAIR_24,	ZombatarCategory::ZombatarCategory_FacialHair,	  5, 3,		gZombatarDimPalletes},
    
	{ZombatarItem::ZOMBATAR_TIDBIT_1,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_1,			ZombatarCategory::ZombatarCategory_Tidbits,		  0, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_TIDBIT_2,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_2,			ZombatarCategory::ZombatarCategory_Tidbits,		  1, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_TIDBIT_3,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_3,			ZombatarCategory::ZombatarCategory_Tidbits,		  2, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_TIDBIT_4,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_4,			ZombatarCategory::ZombatarCategory_Tidbits,		  3, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_5,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_5,			ZombatarCategory::ZombatarCategory_Tidbits,		  4, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_6,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_6,			ZombatarCategory::ZombatarCategory_Tidbits,		  5, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_7,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_7,			ZombatarCategory::ZombatarCategory_Tidbits,		  0, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_8,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_8,			ZombatarCategory::ZombatarCategory_Tidbits,		  1, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_9,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_9,			ZombatarCategory::ZombatarCategory_Tidbits,		  2, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_10,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_10,			ZombatarCategory::ZombatarCategory_Tidbits,		  3, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_11,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_11,			ZombatarCategory::ZombatarCategory_Tidbits,		  4, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_12,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_12,			ZombatarCategory::ZombatarCategory_Tidbits,		  5, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_13,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_13,			ZombatarCategory::ZombatarCategory_Tidbits,		  0, 2,		nullptr},
	{ZombatarItem::ZOMBATAR_TIDBIT_14,				nullptr,							&Sexy::IMAGE_ZOMBATAR_TIDBITS_14,			ZombatarCategory::ZombatarCategory_Tidbits,		  1, 2,		nullptr},

	{ZombatarItem::ZOMBATAR_EYEWEAR_1,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_1,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_1_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  0, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_2,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_2,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_2_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  1, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_3,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_3,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_3_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  2, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_4,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_4,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_4_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  3, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_5,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_5,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_5_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  4, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_6,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_6,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_6_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  5, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_7,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_7,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_7_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  0, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_8,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_8,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_8_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  1, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_9,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_9,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_9_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  2, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_10,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_10,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_10_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  3, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_11,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_11,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_11_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  4, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_12,				&Sexy::IMAGE_ZOMBATAR_EYEWEAR_12,	&Sexy::IMAGE_ZOMBATAR_EYEWEAR_12_MASK,		ZombatarCategory::ZombatarCategory_EyeWears,	  5, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_EYEWEAR_13,				nullptr,							&Sexy::IMAGE_ZOMBATAR_EYEWEAR_13,			ZombatarCategory::ZombatarCategory_EyeWears,	  0, 2,		nullptr},
	{ZombatarItem::ZOMBATAR_EYEWEAR_14,				nullptr,							&Sexy::IMAGE_ZOMBATAR_EYEWEAR_14,			ZombatarCategory::ZombatarCategory_EyeWears,	  1, 2,		nullptr},
	{ZombatarItem::ZOMBATAR_EYEWEAR_15,				nullptr,							&Sexy::IMAGE_ZOMBATAR_EYEWEAR_15,			ZombatarCategory::ZombatarCategory_EyeWears,	  2, 2,		nullptr},
	{ZombatarItem::ZOMBATAR_EYEWEAR_16,				nullptr,							&Sexy::IMAGE_ZOMBATAR_EYEWEAR_16,			ZombatarCategory::ZombatarCategory_EyeWears,	  3, 2,		nullptr},

	{ZombatarItem::ZOMBATAR_CLOTHE_1,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_1,			ZombatarCategory::ZombatarCategory_Clothes,		  0, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_2,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_2,			ZombatarCategory::ZombatarCategory_Clothes,		  1, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_3,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_3,			ZombatarCategory::ZombatarCategory_Clothes,		  2, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_4,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_4,			ZombatarCategory::ZombatarCategory_Clothes,		  3, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_5,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_5,			ZombatarCategory::ZombatarCategory_Clothes,		  4, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_6,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_6,			ZombatarCategory::ZombatarCategory_Clothes,		  5, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_7,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_7,			ZombatarCategory::ZombatarCategory_Clothes,		  0, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_8,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_8,			ZombatarCategory::ZombatarCategory_Clothes,		  1, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_9,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_9,			ZombatarCategory::ZombatarCategory_Clothes,		  2, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_10,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_10,			ZombatarCategory::ZombatarCategory_Clothes,		  3, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_11,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_11,			ZombatarCategory::ZombatarCategory_Clothes,		  4, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_CLOTHE_12,				nullptr,							&Sexy::IMAGE_ZOMBATAR_CLOTHES_12,			ZombatarCategory::ZombatarCategory_Clothes,		  5, 1,		nullptr},

	{ZombatarItem::ZOMBATAR_ACCESSORY_1,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_1,			ZombatarCategory::ZombatarCategory_Accessories,	  0, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_2,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_2,			ZombatarCategory::ZombatarCategory_Accessories,	  1, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_3,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_3,			ZombatarCategory::ZombatarCategory_Accessories,	  2, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_4,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_4,			ZombatarCategory::ZombatarCategory_Accessories,	  3, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_5,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_5,			ZombatarCategory::ZombatarCategory_Accessories,	  4, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_6,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_6,			ZombatarCategory::ZombatarCategory_Accessories,	  5, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_7,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_8,			ZombatarCategory::ZombatarCategory_Accessories,	  0, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_8,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_9,			ZombatarCategory::ZombatarCategory_Accessories,	  1, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_ACCESSORY_9,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_10,			ZombatarCategory::ZombatarCategory_Accessories,	  2, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_10,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_11,			ZombatarCategory::ZombatarCategory_Accessories,	  3, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_ACCESSORY_11,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_12,			ZombatarCategory::ZombatarCategory_Accessories,	  4, 1,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_12,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_13,			ZombatarCategory::ZombatarCategory_Accessories,	  5, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_ACCESSORY_13,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_14,			ZombatarCategory::ZombatarCategory_Accessories,	  0, 2,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_ACCESSORY_14,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_15,			ZombatarCategory::ZombatarCategory_Accessories,	  1, 2,		nullptr},
	{ZombatarItem::ZOMBATAR_ACCESSORY_15,			nullptr,							&Sexy::IMAGE_ZOMBATAR_ACCESSORY_16,			ZombatarCategory::ZombatarCategory_Accessories,	  2, 2,		nullptr},

	{ZombatarItem::ZOMBATAR_HAT_1,					&Sexy::IMAGE_ZOMBATAR_HATS_1,		&Sexy::IMAGE_ZOMBATAR_HATS_1_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  0, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_2,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_2,				ZombatarCategory::ZombatarCategory_Hats,		  1, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_3,					&Sexy::IMAGE_ZOMBATAR_HATS_3,		&Sexy::IMAGE_ZOMBATAR_HATS_3_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  2, 0,		nullptr},
	{ZombatarItem::ZOMBATAR_HAT_4,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_4,				ZombatarCategory::ZombatarCategory_Hats,		  3, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_5,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_5,				ZombatarCategory::ZombatarCategory_Hats,		  4, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_6,					&Sexy::IMAGE_ZOMBATAR_HATS_6,		&Sexy::IMAGE_ZOMBATAR_HATS_6_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  5, 0,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_7,					&Sexy::IMAGE_ZOMBATAR_HATS_7,		&Sexy::IMAGE_ZOMBATAR_HATS_7_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  0, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_8,					&Sexy::IMAGE_ZOMBATAR_HATS_8,		&Sexy::IMAGE_ZOMBATAR_HATS_8_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  1, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_9,					&Sexy::IMAGE_ZOMBATAR_HATS_9,		&Sexy::IMAGE_ZOMBATAR_HATS_9_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  2, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_10,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_10,				ZombatarCategory::ZombatarCategory_Hats,		  3, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_11,					&Sexy::IMAGE_ZOMBATAR_HATS_11,		&Sexy::IMAGE_ZOMBATAR_HATS_11_MASK,			ZombatarCategory::ZombatarCategory_Hats,		  4, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_12,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_12,				ZombatarCategory::ZombatarCategory_Hats,		  5, 1,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_13,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_13,				ZombatarCategory::ZombatarCategory_Hats,		  0, 2,		gZombatarBrightPalletes},
	{ZombatarItem::ZOMBATAR_HAT_14,					nullptr,							&Sexy::IMAGE_ZOMBATAR_HATS_14,				ZombatarCategory::ZombatarCategory_Hats,		  1, 2,		gZombatarBrightPalletes},
};

ZombatarDefinition& GetZombatarDefinition(ZombatarItem theItem)
{
    return gZombatarDefinitions[(int)theItem];
}
