name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev
    - name: Build
      run: cargo build --release

    - name: Upload to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: pvz-rs-linux
        path: |
          target/release/pvz-portable

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache SDL2_mixer SDK
      uses: actions/cache@v4
      with:
        path: |
          SDL2_mixer-2.6.3/**
        key: ${{ runner.os }}-sdl2-mixer-2.6.3-${{ matrix.target }}
    - name: Build
      run: cargo build --release
    - name: Upload to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: pvz-rs-windows
        path: |
          target/release/*.exe
          target/release/*.dll